<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\HoneyDrunk.Operator.Abstractions\HoneyDrunk.Operator.Abstractions.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HoneyDrunk.Standards" Version="0.2.9" PrivateAssets="all" />
    <PackageReference Include="HoneyDrunk.Standards.Tests" Version="0.2.9" PrivateAssets="all" />
  </ItemGroup>
</Project>
